FROM golang:1.18.6-alpine3.16 AS builder
RUN apk --no-cache add git make bash
RUN git config --global http.version HTTP/1.1
ADD . /go/src/github/csi-attacher
WORKDIR /go/src/github/csi-attacher
RUN make

FROM gcr.io/distroless/static:latest
LABEL maintainers="Kubernetes Authors"
LABEL description="CSI External Attacher"

COPY --from=builder /go/src/github/csi-attacher/bin/csi-attacher csi-attacher
ENTRYPOINT ["/csi-attacher"]